### PR TITLE
notes, syntax

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by geraldb** [comment]
@lucasnuic   sorry - there a way too many in more. happy to add more to more. the idea is to feature the best alternatives on the front README.  does this make sense? comments? thoughts?  thks for your contributions.

**Comment by lucasnuic** [comment]
Hi @geraldb. 

> sorry - there a way too many in more. happy to add more to more. 

ok.

> the idea is to feature the best alternatives on the front README.

yes.

>  does this make sense?

yes.

>  comments?

I really want to help this repository and I would be happy if my contribution is accepted. I really like markdown, and I have researched a lot academically into alternatives to markdown such as asciidoc, docfx, yaml, plain text and many other formats.

>  thoughts?

My idea was to have a single readme.md file to inform everyone about the markdown alternatives, showing the difference in syntax. And also information about software, libraries or frameworks that use these file formats. For example, the email can be done with html, markdown or plain text. There is a technical specification in IEFT about the recommendation to use text only or mardkwon instead of html in email.


>  thks for your contributions.

thnks too.

**Comment by geraldb** [comment]
@lucasnuic  thks for your comments. here's an offer / idea.   start a new (top-level) page e.g. SYNTAX.md and put everything together in one page as you like and i am happy to  merge / add  your contributions.

**Comment by lucasnuic** [comment]
> here's an offer / idea. start a new (top-level) page e.g. SYNTAX.md and put everything together in one page as you like and i am happy to merge / add your contributions.

thks for your comments again.

**Comment by lucasnuic** [comment]
see this: https://github.com/mundimark/awesome-markdown-alternatives/pull/9

**Pull request closed without merging**
